
package br.com.correios.webservice.resource;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://resource.webservice.correios.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param usuario
     * @param tipo
     * @param resultado
     * @param lingua
     * @param senha
     * @param objetos
     * @return
     *     returns br.com.correios.webservice.resource.Sroxml
     */
    @WebMethod(action = "buscaEventos")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscaEventos", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.correios.webservice.resource.BuscaEventos")
    @ResponseWrapper(localName = "buscaEventosResponse", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.correios.webservice.resource.BuscaEventosResponse")
    @Action(input = "buscaEventos", output = "http://resource.webservice.correios.com.br/Service/buscaEventosResponse")
    public Sroxml buscaEventos(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "resultado", targetNamespace = "")
        String resultado,
        @WebParam(name = "lingua", targetNamespace = "")
        String lingua,
        @WebParam(name = "objetos", targetNamespace = "")
        String objetos);

    /**
     * 
     * @param usuario
     * @param tipo
     * @param resultado
     * @param lingua
     * @param senha
     * @param objetos
     * @return
     *     returns br.com.correios.webservice.resource.Sroxml
     */
    @WebMethod(action = "buscaEventosLista")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscaEventosLista", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.correios.webservice.resource.BuscaEventosLista")
    @ResponseWrapper(localName = "buscaEventosListaResponse", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.correios.webservice.resource.BuscaEventosListaResponse")
    @Action(input = "buscaEventosLista", output = "http://resource.webservice.correios.com.br/Service/buscaEventosListaResponse")
    public Sroxml buscaEventosLista(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "resultado", targetNamespace = "")
        String resultado,
        @WebParam(name = "lingua", targetNamespace = "")
        String lingua,
        @WebParam(name = "objetos", targetNamespace = "")
        List<String> objetos);

    /**
     * 
     * @param usuario
     * @param tipo
     * @param resultado
     * @param lingua
     * @param senha
     * @param objetos
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RastroJson", action = "RastroJson")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RastroJson", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.correios.webservice.resource.RastroJson")
    @ResponseWrapper(localName = "RastroJsonResponse", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.correios.webservice.resource.RastroJsonResponse")
    @Action(input = "RastroJson", output = "http://resource.webservice.correios.com.br/Service/RastroJsonResponse")
    public String rastroJson(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "resultado", targetNamespace = "")
        String resultado,
        @WebParam(name = "lingua", targetNamespace = "")
        String lingua,
        @WebParam(name = "objetos", targetNamespace = "")
        String objetos);

    /**
     * 
     * @param loec
     * @return
     *     returns br.com.correios.webservice.resource.ListaEntregaExterna2
     */
    @WebMethod(operationName = "ListaEntregaExterna", action = "ListaEntregaExterna")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListaEntregaExterna", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.correios.webservice.resource.ListaEntregaExterna")
    @ResponseWrapper(localName = "ListaEntregaExternaResponse", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.correios.webservice.resource.ListaEntregaExternaResponse")
    @Action(input = "ListaEntregaExterna", output = "http://resource.webservice.correios.com.br/Service/ListaEntregaExternaResponse")
    public ListaEntregaExterna2 listaEntregaExterna(
        @WebParam(name = "loec", targetNamespace = "")
        String loec);

    /**
     * 
     * @param codigoSRO
     * @return
     *     returns java.util.List<br.com.correios.webservice.resource.RegistroUnidades>
     */
    @WebMethod(operationName = "UnidadesSRO", action = "UnidadesSRO")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UnidadesSRO", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.correios.webservice.resource.UnidadesSRO")
    @ResponseWrapper(localName = "UnidadesSROResponse", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.correios.webservice.resource.UnidadesSROResponse")
    @Action(input = "UnidadesSRO", output = "http://resource.webservice.correios.com.br/Service/UnidadesSROResponse")
    public List<RegistroUnidades> unidadesSRO(
        @WebParam(name = "codigoSRO", targetNamespace = "")
        String codigoSRO);

}
