//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.07 at 04:22:37 PM BRT
//


package br.com.correios.api.postagem.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.persistence.oxm.annotations.XmlCDATA;
import org.eclipse.persistence.oxm.annotations.XmlMarshalNullRepresentation;
import org.eclipse.persistence.oxm.annotations.XmlNullPolicy;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}nome_destinatario"/>
 *         &lt;element ref="{}telefone_destinatario"/>
 *         &lt;element ref="{}celular_destinatario"/>
 *         &lt;element ref="{}email_destinatario"/>
 *         &lt;element ref="{}logradouro_destinatario"/>
 *         &lt;element ref="{}complemento_destinatario"/>
 *         &lt;element ref="{}numero_end_destinatario"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nomeDestinatario",
    "telefoneDestinatario",
    "celularDestinatario",
    "emailDestinatario",
    "logradouroDestinatario",
    "complementoDestinatario",
    "numeroEndDestinatario"
})
@XmlRootElement(name = "destinatario")
public class Destinatario {

    @XmlElement(name = "nome_destinatario", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String nomeDestinatario;

    @XmlElement(name = "telefone_destinatario", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String telefoneDestinatario = "";

    @XmlElement(name = "celular_destinatario", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String celularDestinatario = "";

    @XmlElement(name = "email_destinatario", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String emailDestinatario;

    @XmlElement(name = "logradouro_destinatario", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String logradouroDestinatario;

    @XmlElement(name = "complemento_destinatario", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String complementoDestinatario;

    @XmlElement(name = "numero_end_destinatario", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String numeroEndDestinatario;

    /**
     * Gets the value of the nomeDestinatario property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomeDestinatario() {
        return nomeDestinatario;
    }

    /**
     * Sets the value of the nomeDestinatario property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomeDestinatario(String value) {
        this.nomeDestinatario = value;
    }

    /**
     * Gets the value of the telefoneDestinatario property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTelefoneDestinatario() {
        return telefoneDestinatario;
    }

    /**
     * Sets the value of the telefoneDestinatario property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTelefoneDestinatario(String value) {
        this.telefoneDestinatario = value;
    }

    /**
     * Gets the value of the celularDestinatario property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCelularDestinatario() {
        return celularDestinatario;
    }

    /**
     * Sets the value of the celularDestinatario property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCelularDestinatario(String value) {
        this.celularDestinatario = value;
    }

    /**
     * Gets the value of the emailDestinatario property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEmailDestinatario() {
        return emailDestinatario;
    }

    /**
     * Sets the value of the emailDestinatario property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEmailDestinatario(String value) {
        this.emailDestinatario = value;
    }

    /**
     * Gets the value of the logradouroDestinatario property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLogradouroDestinatario() {
        return logradouroDestinatario;
    }

    /**
     * Sets the value of the logradouroDestinatario property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLogradouroDestinatario(String value) {
        this.logradouroDestinatario = value;
    }

    /**
     * Gets the value of the complementoDestinatario property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getComplementoDestinatario() {
        return complementoDestinatario;
    }

    /**
     * Sets the value of the complementoDestinatario property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setComplementoDestinatario(String value) {
        this.complementoDestinatario = value;
    }

    /**
     * Gets the value of the numeroEndDestinatario property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNumeroEndDestinatario() {
        return numeroEndDestinatario;
    }

    /**
     * Sets the value of the numeroEndDestinatario property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNumeroEndDestinatario(String value) {
        this.numeroEndDestinatario = value;
    }

}
