//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.07 at 04:22:37 PM BRT
//


package br.com.correios.api.postagem.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.persistence.oxm.annotations.XmlMarshalNullRepresentation;
import org.eclipse.persistence.oxm.annotations.XmlNullPolicy;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipo_objeto">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;enumeration value="001"/>
 *               &lt;enumeration value="002"/>
 *               &lt;enumeration value="003"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{}dimensao_altura"/>
 *         &lt;element ref="{}dimensao_largura"/>
 *         &lt;element ref="{}dimensao_comprimento"/>
 *         &lt;element ref="{}dimensao_diametro"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipoObjeto",
    "dimensaoAltura",
    "dimensaoLargura",
    "dimensaoComprimento",
    "dimensaoDiametro"
})
@XmlRootElement(name = "dimensao_objeto")
public class DimensaoObjeto {

    @XmlElement(name = "tipo_objeto")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected short tipoObjeto;
    @XmlElement(name = "dimensao_altura")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String dimensaoAltura;
    @XmlElement(name = "dimensao_largura")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String dimensaoLargura;
    @XmlElement(name = "dimensao_comprimento")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String dimensaoComprimento;
    @XmlElement(name = "dimensao_diametro")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected int dimensaoDiametro;

    /**
     * Gets the value of the tipoObjeto property.
     *
     */
    public short getTipoObjeto() {
        return tipoObjeto;
    }

    /**
     * Sets the value of the tipoObjeto property.
     *
     */
    public void setTipoObjeto(short value) {
        this.tipoObjeto = value;
    }

    /**
     * Gets the value of the dimensaoAltura property.
     *
     */
    public String getDimensaoAltura() {
        return dimensaoAltura;
    }

    /**
     * Sets the value of the dimensaoAltura property.
     *
     */
    public void setDimensaoAltura(String value) {
        this.dimensaoAltura = value;
    }

    /**
     * Gets the value of the dimensaoLargura property.
     *
     */
    public String getDimensaoLargura() {
        return dimensaoLargura;
    }

    /**
     * Sets the value of the dimensaoLargura property.
     *
     */
    public void setDimensaoLargura(String value) {
        this.dimensaoLargura = value;
    }

    /**
     * Gets the value of the dimensaoComprimento property.
     *
     */
    public String getDimensaoComprimento() {
        return dimensaoComprimento;
    }

    /**
     * Sets the value of the dimensaoComprimento property.
     *
     */
    public void setDimensaoComprimento(String value) {
        this.dimensaoComprimento = value;
    }

    /**
     * Gets the value of the dimensaoDiametro property.
     *
     */
    public int getDimensaoDiametro() {
        return dimensaoDiametro;
    }

    /**
     * Sets the value of the dimensaoDiametro property.
     *
     */
    public void setDimensaoDiametro(int value) {
        this.dimensaoDiametro = value;
    }

}
