//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.07 at 04:22:37 PM BRT
//


package br.com.correios.api.postagem.xml;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.persistence.oxm.annotations.XmlMarshalNullRepresentation;
import org.eclipse.persistence.oxm.annotations.XmlNullPolicy;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}numero_etiqueta"/>
 *         &lt;element ref="{}codigo_objeto_cliente"/>
 *         &lt;element ref="{}codigo_servico_postagem"/>
 *         &lt;element ref="{}cubagem"/>
 *         &lt;element ref="{}peso"/>
 *         &lt;element ref="{}rt1"/>
 *         &lt;element ref="{}rt2"/>
 *         &lt;element ref="{}destinatario"/>
 *         &lt;element ref="{}nacional"/>
 *         &lt;element ref="{}servico_adicional"/>
 *         &lt;element ref="{}dimensao_objeto"/>
 *         &lt;element ref="{}data_postagem_sara"/>
 *         &lt;element ref="{}status_processamento"/>
 *         &lt;element ref="{}numero_comprovante_postagem"/>
 *         &lt;element ref="{}valor_cobrado"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numeroEtiqueta",
    "codigoObjetoCliente",
    "codigoServicoPostagem",
    "cubagem",
    "peso",
    "rt1",
    "rt2",
    "destinatario",
    "nacional",
    "servicoAdicional",
    "dimensaoObjeto",
    "dataPostagemSara",
    "statusProcessamento",
    "numeroComprovantePostagem",
    "valorCobrado"
})
@XmlRootElement(name = "objeto_postal")
public class ObjetoPostal {

    @XmlElement(name = "numero_etiqueta", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String numeroEtiqueta;

    @XmlElement(name = "codigo_objeto_cliente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String codigoObjetoCliente;

    @XmlElement(name = "codigo_servico_postagem", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String codigoServicoPostagem;

    @XmlElement(required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String cubagem;

    @XmlElement(required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected BigInteger peso;

    @XmlElement(required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String rt1;

    @XmlElement(required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String rt2;

    @XmlElement(required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected Destinatario destinatario;

    @XmlElement(required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected Nacional nacional;

    @XmlElement(name = "servico_adicional", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected ServicoAdicional servicoAdicional;

    @XmlElement(name = "dimensao_objeto", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected DimensaoObjeto dimensaoObjeto;

    @XmlElement(name = "data_postagem_sara", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String dataPostagemSara;

    @XmlElement(name = "status_processamento")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected byte statusProcessamento;

    @XmlElement(name = "numero_comprovante_postagem", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String numeroComprovantePostagem;

    @XmlElement(name = "valor_cobrado", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String valorCobrado;

    /**
     * Gets the value of the numeroEtiqueta property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNumeroEtiqueta() {
        return numeroEtiqueta;
    }

    /**
     * Sets the value of the numeroEtiqueta property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNumeroEtiqueta(String value) {
        this.numeroEtiqueta = value;
    }

    /**
     * Gets the value of the codigoObjetoCliente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoObjetoCliente() {
        return codigoObjetoCliente;
    }

    /**
     * Sets the value of the codigoObjetoCliente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoObjetoCliente(String value) {
        this.codigoObjetoCliente = value;
    }

    /**
     * Gets the value of the codigoServicoPostagem property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoServicoPostagem() {
        return codigoServicoPostagem;
    }

    /**
     * Sets the value of the codigoServicoPostagem property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoServicoPostagem(String value) {
        this.codigoServicoPostagem = value;
    }

    /**
     * Gets the value of the cubagem property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCubagem() {
        return cubagem;
    }

    /**
     * Sets the value of the cubagem property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCubagem(String value) {
        this.cubagem = value;
    }

    /**
     * Gets the value of the peso property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getPeso() {
        return peso;
    }

    /**
     * Sets the value of the peso property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setPeso(BigInteger value) {
        this.peso = value;
    }

    /**
     * Gets the value of the rt1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRt1() {
        return rt1;
    }

    /**
     * Sets the value of the rt1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRt1(String value) {
        this.rt1 = value;
    }

    /**
     * Gets the value of the rt2 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRt2() {
        return rt2;
    }

    /**
     * Sets the value of the rt2 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRt2(String value) {
        this.rt2 = value;
    }

    /**
     * Gets the value of the destinatario property.
     *
     * @return
     *     possible object is
     *     {@link Destinatario }
     *
     */
    public Destinatario getDestinatario() {
        return destinatario;
    }

    /**
     * Sets the value of the destinatario property.
     *
     * @param value
     *     allowed object is
     *     {@link Destinatario }
     *
     */
    public void setDestinatario(Destinatario value) {
        this.destinatario = value;
    }

    /**
     * Gets the value of the nacional property.
     *
     * @return
     *     possible object is
     *     {@link Nacional }
     *
     */
    public Nacional getNacional() {
        return nacional;
    }

    /**
     * Sets the value of the nacional property.
     *
     * @param value
     *     allowed object is
     *     {@link Nacional }
     *
     */
    public void setNacional(Nacional value) {
        this.nacional = value;
    }

    /**
     * Gets the value of the servicoAdicional property.
     *
     * @return
     *     possible object is
     *     {@link ServicoAdicional }
     *
     */
    public ServicoAdicional getServicoAdicional() {
        return servicoAdicional;
    }

    /**
     * Sets the value of the servicoAdicional property.
     *
     * @param value
     *     allowed object is
     *     {@link ServicoAdicional }
     *
     */
    public void setServicoAdicional(ServicoAdicional value) {
        this.servicoAdicional = value;
    }

    /**
     * Gets the value of the dimensaoObjeto property.
     *
     * @return
     *     possible object is
     *     {@link DimensaoObjeto }
     *
     */
    public DimensaoObjeto getDimensaoObjeto() {
        return dimensaoObjeto;
    }

    /**
     * Sets the value of the dimensaoObjeto property.
     *
     * @param value
     *     allowed object is
     *     {@link DimensaoObjeto }
     *
     */
    public void setDimensaoObjeto(DimensaoObjeto value) {
        this.dimensaoObjeto = value;
    }

    /**
     * Gets the value of the dataPostagemSara property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDataPostagemSara() {
        return dataPostagemSara;
    }

    /**
     * Sets the value of the dataPostagemSara property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDataPostagemSara(String value) {
        this.dataPostagemSara = value;
    }

    /**
     * Gets the value of the statusProcessamento property.
     *
     */
    public byte getStatusProcessamento() {
        return statusProcessamento;
    }

    /**
     * Sets the value of the statusProcessamento property.
     *
     */
    public void setStatusProcessamento(byte value) {
        this.statusProcessamento = value;
    }

    /**
     * Gets the value of the numeroComprovantePostagem property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNumeroComprovantePostagem() {
        return numeroComprovantePostagem;
    }

    /**
     * Sets the value of the numeroComprovantePostagem property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNumeroComprovantePostagem(String value) {
        this.numeroComprovantePostagem = value;
    }

    /**
     * Gets the value of the valorCobrado property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValorCobrado() {
        return valorCobrado;
    }

    /**
     * Sets the value of the valorCobrado property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValorCobrado(String value) {
        this.valorCobrado = value;
    }

}
