//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.07 at 04:22:37 PM BRT
//


package br.com.correios.api.postagem.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.persistence.oxm.annotations.XmlCDATA;
import org.eclipse.persistence.oxm.annotations.XmlMarshalNullRepresentation;
import org.eclipse.persistence.oxm.annotations.XmlNullPolicy;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}numero_contrato"/>
 *         &lt;element ref="{}numero_diretoria"/>
 *         &lt;element ref="{}codigo_administrativo"/>
 *         &lt;element ref="{}nome_remetente"/>
 *         &lt;element ref="{}logradouro_remetente"/>
 *         &lt;element ref="{}numero_remetente"/>
 *         &lt;element ref="{}complemento_remetente"/>
 *         &lt;element ref="{}bairro_remetente"/>
 *         &lt;element ref="{}cep_remetente"/>
 *         &lt;element ref="{}cidade_remetente"/>
 *         &lt;element ref="{}uf_remetente"/>
 *         &lt;element ref="{}telefone_remetente"/>
 *         &lt;element ref="{}fax_remetente"/>
 *         &lt;element ref="{}email_remetente"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numeroContrato",
    "numeroDiretoria",
    "codigoAdministrativo",
    "nomeRemetente",
    "logradouroRemetente",
    "numeroRemetente",
    "complementoRemetente",
    "bairroRemetente",
    "cepRemetente",
    "cidadeRemetente",
    "ufRemetente",
    "telefoneRemetente",
    "faxRemetente",
    "emailRemetente"
})
@XmlRootElement(name = "remetente")
public class Remetente {

    @XmlElement(name = "numero_contrato", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String numeroContrato;

    @XmlElement(name = "numero_diretoria")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected byte numeroDiretoria;

    @XmlElement(name = "codigo_administrativo", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String codigoAdministrativo;

    @XmlElement(name = "nome_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String nomeRemetente = "";

    @XmlElement(name = "logradouro_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String logradouroRemetente = "";

    @XmlElement(name = "numero_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String numeroRemetente = "";

    @XmlElement(name = "complemento_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String complementoRemetente = "";

    @XmlElement(name = "bairro_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String bairroRemetente = "";

    @XmlElement(name = "cep_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String cepRemetente = "";

    @XmlElement(name = "cidade_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String cidadeRemetente = "";

    @XmlElement(name = "uf_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String ufRemetente = "";

    @XmlElement(name = "telefone_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String telefoneRemetente = "";

    @XmlElement(name = "fax_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String faxRemetente = "";

    @XmlElement(name = "email_remetente", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    @XmlCDATA
    protected String emailRemetente = "";

    /**
     * Gets the value of the numeroContrato property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNumeroContrato() {
        return numeroContrato;
    }

    /**
     * Sets the value of the numeroContrato property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNumeroContrato(String value) {
        this.numeroContrato = value;
    }

    /**
     * Gets the value of the numeroDiretoria property.
     *
     */
    public byte getNumeroDiretoria() {
        return numeroDiretoria;
    }

    /**
     * Sets the value of the numeroDiretoria property.
     *
     */
    public void setNumeroDiretoria(byte value) {
        this.numeroDiretoria = value;
    }

    /**
     * Gets the value of the codigoAdministrativo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoAdministrativo() {
        return codigoAdministrativo;
    }

    /**
     * Sets the value of the codigoAdministrativo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoAdministrativo(String value) {
        this.codigoAdministrativo = value;
    }

    /**
     * Gets the value of the nomeRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomeRemetente() {
        return nomeRemetente;
    }

    /**
     * Sets the value of the nomeRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomeRemetente(String value) {
        this.nomeRemetente = value;
    }

    /**
     * Gets the value of the logradouroRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLogradouroRemetente() {
        return logradouroRemetente;
    }

    /**
     * Sets the value of the logradouroRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLogradouroRemetente(String value) {
        this.logradouroRemetente = value;
    }

    /**
     * Gets the value of the numeroRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNumeroRemetente() {
        return numeroRemetente;
    }

    /**
     * Sets the value of the numeroRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNumeroRemetente(String value) {
        this.numeroRemetente = value;
    }

    /**
     * Gets the value of the complementoRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getComplementoRemetente() {
        return complementoRemetente;
    }

    /**
     * Sets the value of the complementoRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setComplementoRemetente(String value) {
        this.complementoRemetente = value;
    }

    /**
     * Gets the value of the bairroRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBairroRemetente() {
        return bairroRemetente;
    }

    /**
     * Sets the value of the bairroRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBairroRemetente(String value) {
        this.bairroRemetente = value;
    }

    /**
     * Gets the value of the cepRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCepRemetente() {
        return cepRemetente;
    }

    /**
     * Sets the value of the cepRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCepRemetente(String value) {
        this.cepRemetente = value;
    }

    /**
     * Gets the value of the cidadeRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCidadeRemetente() {
        return cidadeRemetente;
    }

    /**
     * Sets the value of the cidadeRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCidadeRemetente(String value) {
        this.cidadeRemetente = value;
    }

    /**
     * Gets the value of the ufRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUfRemetente() {
        return ufRemetente;
    }

    /**
     * Sets the value of the ufRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUfRemetente(String value) {
        this.ufRemetente = value;
    }

    /**
     * Gets the value of the telefoneRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTelefoneRemetente() {
        return telefoneRemetente;
    }

    /**
     * Sets the value of the telefoneRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTelefoneRemetente(String value) {
        this.telefoneRemetente = value;
    }

    /**
     * Gets the value of the faxRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFaxRemetente() {
        return faxRemetente;
    }

    /**
     * Sets the value of the faxRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFaxRemetente(String value) {
        this.faxRemetente = value;
    }

    /**
     * Gets the value of the emailRemetente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEmailRemetente() {
        return emailRemetente;
    }

    /**
     * Sets the value of the emailRemetente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEmailRemetente(String value) {
        this.emailRemetente = value;
    }

}
