//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.07 at 04:22:37 PM BRT
//


package br.com.correios.api.postagem.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.persistence.oxm.annotations.XmlMarshalNullRepresentation;
import org.eclipse.persistence.oxm.annotations.XmlNullPolicy;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}codigo_servico_adicional" maxOccurs="4"/>
 *         &lt;element ref="{}valor_declarado"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoServicoAdicional",
    "valorDeclarado"
})
@XmlRootElement(name = "servico_adicional")
public class ServicoAdicional {

    @XmlElement(name = "codigo_servico_adicional", type = Short.class)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected List<String> codigoServicoAdicional;
    @XmlElement(name = "valor_declarado", required = true)
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE)
    protected String valorDeclarado;

    /**
     * Gets the value of the codigoServicoAdicional property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codigoServicoAdicional property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodigoServicoAdicional().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     *
     *
     */
    public List<String> getCodigoServicoAdicional() {
        if (codigoServicoAdicional == null) {
            codigoServicoAdicional = new ArrayList<String>();
        }
        return this.codigoServicoAdicional;
    }

    /**
     * Gets the value of the valorDeclarado property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValorDeclarado() {
        return valorDeclarado;
    }

    /**
     * Sets the value of the valorDeclarado property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValorDeclarado(String value) {
        this.valorDeclarado = value;
    }

}
