
package br.com.correios.webservice.postagem;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebFault(name = "SQLException", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class SQLException_Exception
    extends java.lang.Exception
{

	private static final long serialVersionUID = -8676187739818948570L;

	/**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private SQLException faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public SQLException_Exception(String message, SQLException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SQLException_Exception(String message, SQLException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: br.com.correios.webservice.postagem.SQLException
     */
    public SQLException getFaultInfo() {
        return faultInfo;
    }

}
