
package br.com.correios.webservice.rastreio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "rastro", targetNamespace = "http://resource.webservice.correios.com.br/", wsdlLocation = "https://webservice.correios.com.br/service/rastro/Rastro.wsdl")
public class Rastro
    extends javax.xml.ws.Service
{

    private final static URL RASTRO_WSDL_LOCATION;
    private final static WebServiceException RASTRO_EXCEPTION;
    private final static QName RASTRO_QNAME = new QName("http://resource.webservice.correios.com.br/", "rastro");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://webservice.correios.com.br/service/rastro/Rastro.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RASTRO_WSDL_LOCATION = url;
        RASTRO_EXCEPTION = e;
    }

    public Rastro() {
        super(__getWsdlLocation(), RASTRO_QNAME);
    }

    public Rastro(WebServiceFeature... features) {
        super(__getWsdlLocation(), RASTRO_QNAME, features);
    }

    public Rastro(URL wsdlLocation) {
        super(wsdlLocation, RASTRO_QNAME);
    }

    public Rastro(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RASTRO_QNAME, features);
    }

    public Rastro(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Rastro(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServicePort")
    public br.com.correios.webservice.rastreio.Service getServicePort() {
        return super.getPort(new QName("http://resource.webservice.correios.com.br/", "ServicePort"), Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServicePort")
    public br.com.correios.webservice.rastreio.Service getServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resource.webservice.correios.com.br/", "ServicePort"), Service.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RASTRO_EXCEPTION!= null) {
            throw RASTRO_EXCEPTION;
        }
        return RASTRO_WSDL_LOCATION;
    }

}
